services:
  db:
    image: postgres:alpine
    container_name: postgresUser
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - compose_network
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - redis_data:/data
    
    networks:
      - compose_network
    
  migrate:
    container_name: migrateAuth
    image: migrate/migrate
    networks:
      - compose_network
    volumes:
      - ./migrations:/migrations 
    command:
      - -path=/migrations
      - -database=${DATABASE_URL}
      - up
    depends_on:
      db:
        condition: service_healthy
  authservice:
    build:
      dockerfile: Dockerfile
    container_name: authservice 
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
      PORT: ${PORT}
    
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - compose_network
      - app

volumes:
  postgres_data:
  redis_data:

networks:
  compose_network:
    driver: bridge
  app: 
    external: true