events {}

http {
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location /auth/ {
            set $auth_backend http://authservice:8080;
            
            proxy_pass $auth_backend$request_uri; 
        }

        location /tasks/ {
            set $task_backend http://taskservice:8081;
            
            proxy_pass $task_backend$request_uri;
        }
    }
}
